### ISSUE TITLE
预览功能失效

### ISSUE THREAD

**Issue by xushaozhi** [hve-notes/hve-notes#11]
Mac,点击预览按钮没反应。
正常是不是应该自动打开浏览器查看文章？

**Comment by EryouHao** [comment]
@xushaozhi 感谢反馈，我这边没有遇到，方便的话，可以加我个微信具体看下什么情况吗？wx: heyqiuxiaobei

qq: 846475472

**Comment by xypisces** [comment]
+1 同样点击预览没效果，就刚装上去就点预览，无反应
