### ISSUE TITLE
博客创建成功但是基本无法显示（二楼有更新，能显示了但是文章无内容）

### ISSUE THREAD

**Issue by kerhbal** [hve-notes/hve-notes#12]
0.7.5，已创建好github page，软件也已设置好可以同步文件上去，但不知道为什么显示有问题，谢谢！

Github Page：
![image](https://user-images.githubusercontent.com/11629684/52001117-af810380-248c-11e9-98f4-1cb62dd42d22.png)

软件设置：
![hve_notes_2019-01-30_12-32-22](https://user-images.githubusercontent.com/11629684/52000782-edc9f300-248b-11e9-9c92-839a4ca058e0.png)

网页效果：
![brave_2019-01-30_12-33-25](https://user-images.githubusercontent.com/11629684/52000800-fa4e4b80-248b-11e9-845d-eb80a873f2aa.png)

点击那篇自带文章：
![brave_2019-01-30_12-33-40](https://user-images.githubusercontent.com/11629684/52000832-0934fe00-248c-11e9-8dd9-934a22ff257a.png)

**Comment by kerhbal** [comment]
过了一段时间能显示了，但是点进去文章无内容
## 软件内的两篇文章
![image](https://user-images.githubusercontent.com/11629684/52001941-ac871280-248e-11e9-8ed4-d9d27c5ec280.png)

![image](https://user-images.githubusercontent.com/11629684/52001955-b3158a00-248e-11e9-9fb4-1c9e996164df.png)

![image](https://user-images.githubusercontent.com/11629684/52001960-bad52e80-248e-11e9-87fc-a313aab6fb46.png)

## 网页显示
![image](https://user-images.githubusercontent.com/11629684/52002084-0a1b5f00-248f-11e9-89d9-d2949ad9f9fd.png)
### 点击后
![image](https://user-images.githubusercontent.com/11629684/52002054-fa037f80-248e-11e9-8dc4-bbf1218079c2.png)

![image](https://user-images.githubusercontent.com/11629684/52002123-23241000-248f-11e9-8c87-fa76eb55db79.png)

**Comment by EryouHao** [comment]
@kerhbal 我看你的主题好像是旧版主题，你之前应该有安装过低版本 <=0.7.0 ? 你把原来的主题文件夹（~/文档/hve-notes/themes 里面的 notes 和 fly 两个文件夹）删除，然后重新启动新版应用再预览看看呢，配置不会覆盖。

若成功了，请记得回复此 issues，感谢支持🙏

**Comment by kerhbal** [comment]
@EryouHao 可以了，非常感谢！
另外想请教一个问题，在软件设置里的域名那里填 kerhbal.github.io 和 kerhbal.github.io/blog 有区别吗？之前试好像都可以。

**Comment by EryouHao** [comment]
有区别。

`kerhbal.github.io` 相当于你的仓库名就是 kerhbal.github.io，github 会自动将此仓库开放 github pages 服务

 `kerhbal.github.io/blog` 相当于你的仓库名是 `blog`,然后你需要手动将 blog 的某个分支，比如 master 分支开启 github pages 服务

**Comment by kerhbal** [comment]
@EryouHao 哦这样啊，谢谢！不过我刚才发现似乎markdown渲染有些问题，文章里的格式都没有经过渲染，比如标题和加粗什么的，都和正文一样。

**Comment by EryouHao** [comment]
@kerhbal 糟糕，主题 css 问题！我已经修复并重新打包了，你可以重新下载安装一下应用，还是当前版本，然后删除 themes 文件夹里面的两个主题，再打开应用就可以了。

或者你可以在这里下载主题，替换掉 themes 文件夹里面对应的 notes 文件夹 https://github.com/hve-notes/notes

**Comment by kerhbal** [comment]
@EryouHao 似乎好了一半。。。加粗的语法好了，但是斜体和标题还有无序列表还是不行

![image](https://user-images.githubusercontent.com/11629684/52030254-fd295a80-24e4-11e9-82ed-311023564aeb.png)


![image](https://user-images.githubusercontent.com/11629684/52030315-3e216f00-24e5-11e9-9596-95edda72b3b3.png)

**Comment by EryouHao** [comment]
💔Sorry, 糟糕的软件质量... 准确的说是粗糙的主题质量。刚刚修复重新发了安装包和更新了主题仓库，可以再更新一下试试。以后这种问题明显问题，欢迎 PR！

主题打磨程度不够

感谢🙏

**Comment by kerhbal** [comment]
@EryouHao 好了，这下可以了，多谢帮助！

**Comment by Houweix** [comment]
大佬，我今天弄了一下，文章也是404，我这是第一次用这个软件，没有之前版本的主题软件主题，等了好久都是404
