### ISSUE TITLE
relasses界面似乎没发布hve-notes 0.75的dmg文件，但程序提示更新

### ISSUE THREAD

**Issue by jimoshizhe** [hve-notes/hve-notes#13]
relasses界面似乎没发布hve-notes 0.75的dmg文件，但程序提示更新
![](https://raw.githubusercontent.com/jimoshizhe/cymtuchuang/master//img/bug.png)

**Comment by EryouHao** [comment]
@jimoshizhe 已经补充，春节老家的网不好，上传遇到问题，感谢支持🙏
