### ISSUE TITLE
腾讯云开发者平台同步失败

### ISSUE THREAD

**Issue by LoRexxar** [hve-notes/hve-notes#14]
coding.net被腾讯收购了已经迁移到了腾讯开发者平台，但研究了一下好像同步不了

https://dev.tencent.com/

https://dev.tencent.com/u/LoRexxar/p/LoRexxar

**Comment by EryouHao** [comment]
应该是分支不是 `master` 的原因，改成 `master` 应该就可以了，或者等下版本修复，感谢🙏

**Comment by LoRexxar** [comment]
我记得以前coding有要求的，分支必须是这个，后来好像没要求了，就一直这样了

**Comment by EryouHao** [comment]
Fixed on [v0.7.6](https://github.com/hve-notes/hve-notes/releases/tag/v0.7.6)
