### ISSUE TITLE
在软件中隐藏了初始化的帖子“Hello Hve Notes”，但还是会显示，麻烦解决

### ISSUE THREAD

**Issue by lolstudio** [hve-notes/hve-notes#15]
链接：https://lolstudio.github.io/
![wx20190219-155546](https://user-images.githubusercontent.com/11715848/52998673-d795ce00-345e-11e9-9fe4-3fc3b12aeef8.png)

![wx20190219-155504](https://user-images.githubusercontent.com/11715848/52998643-c0ef7700-345e-11e9-9ef4-93177da15b37.png)
![wx20190219-155526](https://user-images.githubusercontent.com/11715848/52998655-ca78df00-345e-11e9-9ca9-b3f579e346ee.png)

**Comment by EryouHao** [comment]
@lolstudio 这是因为没有要显示的文章，所以显示了之前渲染的页面，没有渲染新页面。你暂时可以通过删除此文章，并且写自己的文章至少显示一篇文章来使用（理论上不太影响使用），下版本会修复此问题。

感谢支持🙏

**Comment by EryouHao** [comment]
Fixed on [v0.7.6](https://github.com/hve-notes/hve-notes/releases/tag/v0.7.6)
