### ISSUE TITLE
无法同步，提示‘抱歉，同步遇到了错误，请联系作者’

### ISSUE THREAD

**Issue by pipanyuwuqi** [hve-notes/hve-notes#16]
如题

**Comment by EryouHao** [comment]
多半是配置配置错了，或者本地没有安装Git，目前用过的小伙伴出现这个问题的，都是这样的情况。建议可以加群处理下，或按照教程重新搞一下。https://fehey.com/post/hve-notes-start/

感谢支持

**Comment by pipanyuwuqi** [comment]
> 多半是配置配置错了，或者本地没有安装Git，目前用过的小伙伴出现这个问题的，都是这样的情况。建议可以加群处理下，或按照教程重新搞一下。https://fehey.com/post/hve-notes-start/
> 
> 感谢支持

换了一个token就可以了，谢谢。
