### ISSUE TITLE
如何在新的菜单下 发表新文章

### ISSUE THREAD

**Issue by buerlee** [hve-notes/hve-notes#17]
如题。

我是新手，不知道为什么 不能在新的菜单下 发表新文章？

谢谢。

**Comment by EryouHao** [comment]
@buerlee 如果是自定义菜单，可以先新建文章，然后新建菜单后选择那篇文章即可，可以参考应用默认的[关于]文章

**Comment by buerlee** [comment]
谢谢你的回复。我不知道我理解对了你的意思没，按照你说的方法，好像只能选择一篇吧，比如说 我新建一个菜单“日记”，我先把日记相关的放在这里。

**Comment by EryouHao** [comment]
@buerlee 这样的话，其实你可以建个菜单，然后指向某个 Tag 的链接，比如这个链接[年终总结](https://fehey.com/tag/nian-zhong-zong-jie/) 就可以了

**Comment by buerlee** [comment]
Thanks.
