### ISSUE TITLE
安装程序停止工作

### ISSUE THREAD

**Issue by xhufo** [hve-notes/hve-notes#18]
![image](https://user-images.githubusercontent.com/11385342/53534346-6aa6c600-3b39-11e9-9d4b-e40d8bd33a84.png)
请问一下这个问题怎么解决，是不是下载的不对还是其他什么问题，十分感谢！

**Comment by EryouHao** [comment]
@xhufo 请问您是什么系统版本，目前只有 Windows 64位 和 Mac OS 支持

**Comment by xhufo** [comment]
> @xhufo 请问您是什么系统版本，目前只有 Windows 64位 和 Mac OS 支持

Windows64位系统。谢谢不崩了，因为单位电脑上网是要走代理服务器的，找了个前置代理工具跑起来就没这个问题了。配置还有点连接失败的问题，我再研究一下
