### ISSUE TITLE
英文下tag间逗号为中文逗号

### ISSUE THREAD

**Issue by qihao96** [hve-notes/hve-notes#20]
如下所示：

 2019-03-02  python ， vision

tag间定义为英文逗号更为合适。

**Comment by EryouHao** [comment]
看了一下您好想说的是 「fly」主题的tag 分隔符，这个只是简单用了一个符号表示，您可以替换为其他的个人喜欢的符号，文件路径：`~/Documents/hve-notes/themes/fly/templates/includes/post-list.ejs` 第 19 行。

单纯的从中英文逗号来说，主题不是很好做选择，因为，有些人可能都是使用的中文 Tag，这样看是不是中文又合适了。

感谢您的严谨反馈

**Comment by qihao96** [comment]
> 看了一下您好想说的是 「fly」主题的tag 分隔符，这个只是简单用了一个符号表示，您可以替换为其他的个人喜欢的符号，文件路径：`~/Documents/hve-notes/themes/fly/templates/includes/post-list.ejs` 第 19 行。
> 
> 单纯的从中英文逗号来说，主题不是很好做选择，因为，有些人可能都是使用的中文 Tag，这样看是不是中文又合适了。
> 
> 感谢您的严谨反馈

感谢你的工作，已验证并更新到个人博客。
