### ISSUE TITLE
图片加载过慢

### ISSUE THREAD

**Issue by HuDaQian** [hve-notes/hve-notes#21]
sidebar-bg 和 favicon  耗时严重导致打开主页速度很慢。是我配置的问题吗？

**Comment by EryouHao** [comment]
@HuDaQian 速度慢的原因有几个：

1. 资源过大（sidebar-bg 估计你说的 simple 主题的左边图片，这个我制作主题的时候尽量做了压缩）
2. 网络链接 github pages 的速度，比如挂代理的情况下访问就蛮快，国内普通访问速度一般

和配置没什么关系，下个版本会考虑加上文章图片压缩功能

**Comment by HuDaQian** [comment]
> @HuDaQian 速度慢的原因有几个：
> 
>     1. 资源过大（sidebar-bg 估计你说的 simple 主题的左边图片，这个我制作主题的时候尽量做了压缩）
> 
>     2. 网络链接 github pages 的速度，比如挂代理的情况下访问就蛮快，国内普通访问速度一般
> 
> 
> 和配置没什么关系，下个版本会考虑加上文章图片压缩功能

谢谢大佬，明白了。🙏
