### ISSUE TITLE
首页链接不对

### ISSUE THREAD

**Issue by yangweijie** [hve-notes/hve-notes#23]
https://yangweijie.github.io/note/
![image](https://user-images.githubusercontent.com/1614114/54013620-cb2aa880-41b4-11e9-9593-1dfd40a9edd4.png)
设置了链接 必须带note
![image](https://user-images.githubusercontent.com/1614114/54013635-d978c480-41b4-11e9-9f54-b3a4877556bc.png)

菜单的链接也带note

同步后，生成的首页不带note
![image](https://user-images.githubusercontent.com/1614114/54013647-e39ac300-41b4-11e9-983c-ed7276940485.png)
点进详情带note  这不一致啊。
![image](https://user-images.githubusercontent.com/1614114/54013663-f614fc80-41b4-11e9-9d33-9a3fff109129.png)

**Comment by EryouHao** [comment]
我点了下你的博客连接，好像正常了？

另外设置首页、归档、标签这几个链接时，可通过下拉选择，快速选择来进行设置，都是用的绝对路径

![image](https://user-images.githubusercontent.com/17328747/54014031-34f78200-41b6-11e9-83d0-1ef4d7e7d78d.png)
