### ISSUE TITLE
tag的候选应该不区分大小写

### ISSUE THREAD

**Issue by yangweijie** [hve-notes/hve-notes#25]
tag的候选应该不区分大小  专有名词 如 SQL  应该小写标签也能搜索出来，毕竟不会定义全大写和全小写的同意义的标签。

**Comment by EryouHao** [comment]
![image](https://user-images.githubusercontent.com/17328747/55271855-f9506380-52ee-11e9-9a47-126bf88c7f9d.png)
我试了一下，是可以搜索出来的，不知道说的是不是这个
