### ISSUE TITLE
[Bug] Windows 界面 Icon 加载失败？

### ISSUE THREAD

**Issue by rosuH** [hve-notes/hve-notes#5]
# 环境
- Win10 x64 pro 1809
- 0.6.3 版本

# 现象描述

![image](https://user-images.githubusercontent.com/15865017/50907641-d4bcbc00-1462-11e9-86ad-e457c795a765.png)

![image](https://user-images.githubusercontent.com/15865017/50907671-ebfba980-1462-11e9-9e6a-30e20eb7a87e.png)

看起来是 icon 加载失败了吗？

**Comment by EryouHao** [comment]
@rosuH 是的，应该是 material icons 被墙了，下个版本修复一下，换成国内 cdn，没考虑周全。

**Comment by rosuH** [comment]
@EryouHao 竟然用的是在线 icon 吗？直接打包进去会不会是一种更好的解决方法？

**Comment by EryouHao** [comment]
@rosuH 是在线的，我看你是用的 windows 版，临时重新构建了一个 windows 的安装包，已经打包进去了，版本还是 v0.6.3 你可以重新下载安装试一下，感谢反馈❤

https://github.com/hve-notes/hve-notes/releases
