### ISSUE TITLE
[UI] Favicon 设置界面按钮上下没有对齐

### ISSUE THREAD

**Issue by rosuH** [hve-notes/hve-notes#6]
如图：
![image](https://user-images.githubusercontent.com/15865017/50939754-15dfbb00-14b9-11e9-8a4b-cef503b6c5ce.png)

**Comment by EryouHao** [comment]
已进行简单对齐修复（v0.6.3 需重新下载安装），此版本着重实现了功能，一些细节打磨的不够，感谢支持
