### ISSUE TITLE
[Bug] 没有填写部署信息时仍然能够点击发布按钮

### ISSUE THREAD

**Issue by rosuH** [hve-notes/hve-notes#7]
# 环境
- Win10 x64 pro 1809
- 0.6.3 版本

# 现象描述 & 复现步骤

1. 配置页没有填写部署信息
2. 点击发布按钮后“发布”步骤持续进行

# 期望现象

1. 发布前检查配置页配置情况
2. 发布错误提示
3. 发布超时提示

**Comment by EryouHao** [comment]
确实，这个版本一些校验做的不够，会继续完善，感谢反馈

**Comment by EryouHao** [comment]
已经简单修复
